#!/usr/bin/env python3
"""
Build hours-ledger-app.html from app_template.html.

Injects the Hong Kong public holiday table into the template, replacing the
`/*HOLIDAYS*/{}` placeholder. Gazetted years are held here; projected years come
from holidays_projected.py (itself generated by hk_holidays.py).

    python build_app.py [output_path]      # defaults to ../index.html
"""
import json
import sys
from datetime import date
from pathlib import Path

from holidays_projected import PROJECTED

# Official general holidays published by the HKSAR Government (gov.hk).
GAZETTED = {
    2023: [("2023-01-02", "Day following New Year's Day"), ("2023-01-23", "Lunar New Year 2nd day"),
           ("2023-01-24", "Lunar New Year 3rd day"), ("2023-01-25", "Lunar New Year 4th day"),
           ("2023-04-05", "Ching Ming Festival"), ("2023-04-07", "Good Friday"),
           ("2023-04-08", "Day following Good Friday"), ("2023-04-10", "Easter Monday"),
           ("2023-05-01", "Labour Day"), ("2023-05-26", "Birthday of the Buddha"),
           ("2023-06-22", "Tuen Ng Festival"), ("2023-07-01", "HKSAR Establishment Day"),
           ("2023-09-30", "Day following Mid-Autumn Festival"), ("2023-10-02", "Day following National Day"),
           ("2023-10-23", "Chung Yeung Festival"), ("2023-12-25", "Christmas Day"),
           ("2023-12-26", "First weekday after Christmas Day")],
    2024: [("2024-01-01", "The first day of January"), ("2024-02-10", "Lunar New Year's Day"),
           ("2024-02-12", "Lunar New Year 3rd day"), ("2024-02-13", "Lunar New Year 4th day"),
           ("2024-03-29", "Good Friday"), ("2024-03-30", "Day following Good Friday"),
           ("2024-04-01", "Easter Monday"), ("2024-04-04", "Ching Ming Festival"),
           ("2024-05-01", "Labour Day"), ("2024-05-15", "Birthday of the Buddha"),
           ("2024-06-10", "Tuen Ng Festival"), ("2024-07-01", "HKSAR Establishment Day"),
           ("2024-09-18", "Day following Mid-Autumn Festival"), ("2024-10-01", "National Day"),
           ("2024-10-11", "Chung Yeung Festival"), ("2024-12-25", "Christmas Day"),
           ("2024-12-26", "First weekday after Christmas Day")],
    2025: [("2025-01-01", "The first day of January"), ("2025-01-29", "Lunar New Year's Day"),
           ("2025-01-30", "Lunar New Year 2nd day"), ("2025-01-31", "Lunar New Year 3rd day"),
           ("2025-04-04", "Ching Ming Festival"), ("2025-04-18", "Good Friday"),
           ("2025-04-19", "Day following Good Friday"), ("2025-04-21", "Easter Monday"),
           ("2025-05-01", "Labour Day"), ("2025-05-05", "Birthday of the Buddha"),
           ("2025-05-31", "Tuen Ng Festival"), ("2025-07-01", "HKSAR Establishment Day"),
           ("2025-10-01", "National Day"), ("2025-10-07", "Day following Mid-Autumn Festival"),
           ("2025-10-29", "Chung Yeung Festival"), ("2025-12-25", "Christmas Day"),
           ("2025-12-26", "First weekday after Christmas Day")],
    2026: [("2026-01-01", "The first day of January"), ("2026-02-17", "Lunar New Year's Day"),
           ("2026-02-18", "Lunar New Year 2nd day"), ("2026-02-19", "Lunar New Year 3rd day"),
           ("2026-04-03", "Good Friday"), ("2026-04-04", "Day following Good Friday"),
           ("2026-04-06", "Day following Ching Ming Festival"), ("2026-04-07", "Day following Easter Monday"),
           ("2026-05-01", "Labour Day"), ("2026-05-25", "Day following Birthday of the Buddha"),
           ("2026-06-19", "Tuen Ng Festival"), ("2026-07-01", "HKSAR Establishment Day"),
           ("2026-09-26", "Day following Mid-Autumn Festival"), ("2026-10-01", "National Day"),
           ("2026-10-19", "Day following Chung Yeung Festival"), ("2026-12-25", "Christmas Day"),
           ("2026-12-26", "First weekday after Christmas Day")],
    2027: [("2027-01-01", "The first day of January"), ("2027-02-06", "Lunar New Year's Day"),
           ("2027-02-08", "Lunar New Year 3rd day"), ("2027-02-09", "Lunar New Year 4th day"),
           ("2027-03-26", "Good Friday"), ("2027-03-27", "Day following Good Friday"),
           ("2027-03-29", "Easter Monday"), ("2027-04-05", "Ching Ming Festival"),
           ("2027-05-01", "Labour Day"), ("2027-05-13", "Birthday of the Buddha"),
           ("2027-06-09", "Tuen Ng Festival"), ("2027-07-01", "HKSAR Establishment Day"),
           ("2027-09-16", "Day following Mid-Autumn Festival"), ("2027-10-01", "National Day"),
           ("2027-10-08", "Chung Yeung Festival"), ("2027-12-25", "Christmas Day"),
           ("2027-12-27", "First weekday after Christmas Day")],
}

PLACEHOLDER = "/*HOLIDAYS*/{}"


def holiday_table():
    """{'2026': [[iso_date, name, status], ...], ...}"""
    table = {str(y): [[d, n, "Gazetted"] for d, n in rows] for y, rows in GAZETTED.items()}
    table.update({str(y): [[d, n, "Projected"] for d, n in rows] for y, rows in PROJECTED.items()})
    return {k: table[k] for k in sorted(table)}


def check(table):
    """Fail loudly rather than shipping a bad calendar."""
    for year, rows in table.items():
        assert len(rows) == 17, f"{year}: {len(rows)} holidays, expected 17"
        seen = set()
        for iso, name, status in rows:
            d = date.fromisoformat(iso)
            assert d.year == int(year), f"{iso} filed under {year}"
            assert d.weekday() != 6, f"{iso} ({name}) falls on a Sunday"
            assert iso not in seen, f"{iso} duplicated in {year}"
            seen.add(iso)
    return sum(len(v) for v in table.values())


def main():
    here = Path(__file__).parent
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else here.parent / "index.html"

    table = holiday_table()
    total = check(table)

    template = (here / "app_template.html").read_text()
    assert PLACEHOLDER in template, "placeholder missing from app_template.html"
    html = template.replace(PLACEHOLDER, json.dumps(table, separators=(",", ":")))
    assert PLACEHOLDER not in html

    out.write_text(html)
    years = sorted(table)
    gaz = sum(1 for rows in table.values() for r in rows if r[2] == "Gazetted")
    print(f"{out}  {round(len(html)/1024)} KB")
    print(f"{total} holidays, {years[0]}-{years[-1]}  ({gaz} gazetted, {total - gaz} projected)")


if __name__ == "__main__":
    main()
